ci: add node v20
webpack-contrib/mini-css-extract-plugin pull request #1029
Opened 2023-04-19 01:48 UTC by ersachin3112

This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
add node v20

### Breaking Changes
No

### Additional Info
No

2023-04-19 01:51 UTC, snitin315 approved these changes

2023-04-19 02:12 UTC, snitin315 requested changes
Let's update it here too:

https://github.com/webpack-contrib/mini-css-extract-plugin/blob/2985918b79cd05cd5390e8b6d70e2009ea531521/.github/workflows/nodejs.yml#L69

2023-04-22 00:49 UTC, snitin315 approved these changes

2023-04-22 01:28 UTC, alexander-akait approved these changes

2023-04-22 01:28 UTC, merged